// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinI-o9GN8YaHwtJbftN-FlnJo00Ig768',
    appId: '1:858341589904:web:1e032f59e4b4ca9a646915',
    messagingSenderId: '858341589904',
    projectId: 'glitchx-second-project-c05c3',
    authDomain: 'glitchx-second-project-c05c3.firebaseapp.com',
    storageBucket: 'glitchx-second-project-c05c3.firebasestorage.app',
    measurementId: 'G-NYRGVG4PJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5s7ipmfAEDu5yXtiU59IzzbDiFl8Roe8',
    appId: '1:858341589904:android:0810b32784089855646915',
    messagingSenderId: '858341589904',
    projectId: 'glitchx-second-project-c05c3',
    storageBucket: 'glitchx-second-project-c05c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxBrE0DbHsz4L7rbuxnTxbT-Y6Nk2kQ7g',
    appId: '1:858341589904:ios:7f73a9b1cb0d27b7646915',
    messagingSenderId: '858341589904',
    projectId: 'glitchx-second-project-c05c3',
    storageBucket: 'glitchx-second-project-c05c3.firebasestorage.app',
    iosBundleId: 'com.example.glitchx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxBrE0DbHsz4L7rbuxnTxbT-Y6Nk2kQ7g',
    appId: '1:858341589904:ios:7f73a9b1cb0d27b7646915',
    messagingSenderId: '858341589904',
    projectId: 'glitchx-second-project-c05c3',
    storageBucket: 'glitchx-second-project-c05c3.firebasestorage.app',
    iosBundleId: 'com.example.glitchx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAinI-o9GN8YaHwtJbftN-FlnJo00Ig768',
    appId: '1:858341589904:web:a54df8e1c815a602646915',
    messagingSenderId: '858341589904',
    projectId: 'glitchx-second-project-c05c3',
    authDomain: 'glitchx-second-project-c05c3.firebaseapp.com',
    storageBucket: 'glitchx-second-project-c05c3.firebasestorage.app',
    measurementId: 'G-SELGFX2W8H',
  );
}
